# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 237ce79ae4f0ff23a8e9dc0d0ed35a9fd604bc23a0edfd5e9fedfc9e1d8f9f30646a8fc6734a99430718ea0e353ad5df508fc1f249f90ba07e9a7ca8de3faead

test:
  secret_key_base: fc89c29953363a8189f3640988b12603d4c210926caf78ea41ebd6ecf9268efc57b77e35bb13cd7e9c86e328f74e21b0b069bc3b2417afb27242b895adbda39f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
